version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://globant_user:globant_password@db:5432/globant_migration_db
      - POSTGRES_USER=globant_user
      - POSTGRES_PASSWORD=globant_password
      - POSTGRES_DB=globant_migration_db
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - globant_network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=globant_user
      - POSTGRES_PASSWORD=globant_password
      - POSTGRES_DB=globant_migration_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - globant_network

volumes:
  postgres_data:

networks:
  globant_network:
    driver: bridge