"""create_bronze_and_silver_layers

Revision ID: 1ee2ecf83c51
Revises: 
Create Date: 2025-05-04 18:58:34.143915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee2ecf83c51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_departments',
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_department')
    )
    op.create_table('dim_jobs',
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_job')
    )
    op.create_table('stg_departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_hired_employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('datetime', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stg_jobs')
    op.drop_table('stg_hired_employees')
    op.drop_table('stg_departments')
    op.drop_table('dim_jobs')
    op.drop_table('dim_departments')
    # ### end Alembic commands ###
