"""initial_migration

Revision ID: cd128f7188bc
Revises: 
Create Date: 2025-05-06 02:19:00.244159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd128f7188bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_departments',
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_department')
    )
    op.create_table('dim_jobs',
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=100), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_job')
    )
    op.create_table('stg_departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_hired_employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('datetime', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_hired_employees',
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hire_datetime', sa.DateTime(), nullable=False),
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_department'], ['dim_departments.id_department'], name='fk_fact_hired_employees_department', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_job'], ['dim_jobs.id_job'], name='fk_fact_hired_employees_job', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_employee')
    )
    op.create_index('ix_fact_hired_employees_hire_datetime', 'fact_hired_employees', ['hire_datetime'], unique=False)
    op.create_index(op.f('ix_fact_hired_employees_id_department'), 'fact_hired_employees', ['id_department'], unique=False)
    op.create_index(op.f('ix_fact_hired_employees_id_job'), 'fact_hired_employees', ['id_job'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_hired_employees_id_job'), table_name='fact_hired_employees')
    op.drop_index(op.f('ix_fact_hired_employees_id_department'), table_name='fact_hired_employees')
    op.drop_index('ix_fact_hired_employees_hire_datetime', table_name='fact_hired_employees')
    op.drop_table('fact_hired_employees')
    op.drop_table('stg_jobs')
    op.drop_table('stg_hired_employees')
    op.drop_table('stg_departments')
    op.drop_table('dim_jobs')
    op.drop_table('dim_departments')
    # ### end Alembic commands ###
